### ISSUE TITLE
Flexible Content

### ISSUE THREAD

**Issue by Krato** [izi-dev/nova-conditional-if#1]
Thanks for your package. Works very sweet.

I'm trying to use it with [NovaFlexibleContent](https://github.com/whitecube/nova-flexible-content) but is not working. Can you add support?

Thanks!

**Comment by izi-dev** [comment]
thanks, i will check.

@Krato, could you please tell me some more information about your problem?

**Comment by Krato** [comment]
Well, the if is not working inside a Flexible field.

**Comment by izi-dev** [comment]
> Well, the if is not working inside a Flexible field. 


ok, i was testing, unfortunately not possible because: the flexible content pack uses its own way to call its components, it doesn't use the form-panel component which is the component i am overwriting to show or not the fields, At the moment this package cannot solve your request, it would be better if you add this improve to the flexible content package

**Comment by Krato** [comment]
Ok. Thanks for your work
